version: '3'

services:
  mysqlos:
   image: mysql:5.7
   volumes:
    - mysql_storage:/var/lib/mysql
   restart: always
   environment:
    MYSQL_ROOT_PASSWORD: Root@123
    MYSQL_USER: har
    MYSQL_PASSWORD: har
    MYSQL_DATABASE: mydb

  wordpressos:
   image: wordpress:5.1.1-php7.3-apache
   restart: always
   depends_on:
    - mysqlos
   ports:
    - 8081:80
   environment: 
    WORDPRESS_DB_HOST: mysqlos
    WORDPRESS_DB_USER: har
    WORDPRESS_DB_PASSWORD: har
    WORDPRESS_DB_NAME: mydb
   volumes:
    - wp_storage:/var/www/html
volumes:
 wp_storage:
 mysql_storage:
